name: CI/CD to AKS for FastAPI App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: fastapi-app

jobs:

  fs-scan-trivy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scanners: 'vuln,config'
        scan-ref: '.'
        hide-progress: false
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0' # Set to '0' to not fail the job on vulnerabilities
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        trivy-config: trivy.yaml
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  unit-tests:
    needs: fs-scan-trivy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        make test
  
  build-and-push:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI - Login to ACR
      run: |
        az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    
    - name: run Trivy vulnerability scanner in image mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ secrets.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        format: 'table'
        exit-code: '0' # Set to '0' to not fail the job on vulnerabilities
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
  deploy-dev:
    name: Deploy to Dev Environment
    if: github.event_name == 'pull_request'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: http://dev.abdalslamdemo.xyz

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}

    - name: Replace image in manifest and deploy to dev
      run: |
        sed "s|<IMAGE_PLACEHOLDER>|${{ secrets.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml | kubectl apply -n dev -f -
    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/fastapi-app -n dev

  deploy-test:
    name: Deploy to Test Environment
    if: github.event.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest

    environment: 
      name: test
      url: http://test.abdalslamdemo.xyz

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v4
      with:
        # Check the following URLs one by one sequentially
        url: http://test.abdalslamdemo.xyz/health
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: true # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 10 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false # Optional, defaults to "false"

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}

    - name: Replace image in manifest and deploy to test
      run: |
        sed "s|<IMAGE_PLACEHOLDER>|${{ secrets.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml | kubectl apply -n test -f -
        kubectl rollout status deployment/fastapi-app -n test